routes/web.php
<?php
use App\Applicant;
use App\User;
use App\Week;
use App\Store;
use App\Storecat;
use App\Profile;
use App\Exercise;
use App\Exercisecat;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('test', function(){ return '';});

Route::resource('profile', 'ProfileController');
Route::resource('nutrition', 'NutritionController');
Route::resource('nutritioncat', 'NutritioncatController');
Route::resource('exercise', 'ExerciseController');
Route::resource('exercisecat', 'ExercisecatController');
Route::resource('storecat', 'StorecatController');
Route::resource('view-profile', 'ViewProfileController');
Route::resource('categories', 'CategoriesController');
Route::resource('blogs', 'BlogController');

resources/views/plugins/blog-table.blade.php
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" type="text/css">


<table id="profile-table" class="display">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">title</th>
        <th scope="col">img</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    @forelse($blogs as $blog)

        <tr>
            <td>{{$blog->id}}</td>
            <td>{{$blog->title}}</td>
            <td><img src="images/{{$blog->img}}" height="50px"></td>
            <td><a href="{{ route('blogs.show',$blog->id) }}"><button type="button" class="btn btn-dark btn-sm">Edit</button></a></td>
            <td>
                <form action="{{ route('blogs.destroy',$blog->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this exercise?')">Remove</button>
                </form>
            </td>
        </tr>

    @empty

        <p>No blogs</p>

    @endforelse

    <!-- Blog Modal -->

    <div class="modal fade" id="addBlog">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Blog</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('blogs.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <label>Blog Title: </label> <input type="text" name="title" class="form-control" placeholder="e.g: Pushup" required>
                                    <br><br>

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Short Description</label>
                                        <textarea class="form-control" name="short" id="short" rows="2"></textarea>
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Full Article</label>
                                        <textarea class="form-control" name="description" id="description" rows="5"></textarea>
                                    </div>

                                    <input type="file" name="img" class="form-control"  name="Upload Image"/>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary" onclick="tinyMCE.triggerSave(true,true);">Add Recipe</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>



<script src="//code.jquery.com/jquery-3.3.1.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#profile-table').dataTable({

        columnDefs: [{
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        }],
        select: {
            style: 'os',
            selector: 'td:first-child'
        }
    });
</script>

resources/views/plugins/exercise-table.blade.php
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" type="text/css">

<table id="profile-table" class="display">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Exercise Name</th>
        <th scope="col">Category Name</th>
        <th scope="col">Image</th>
       <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    @forelse($exercises as $exercise)

        <tr>
            <td>{{$exercise->id}}</td>
            <td>{{$exercise->exercise}}</td>
            <td>{{$exercise->catagorie_name}}</td>
            <td><img src="images/{{$exercise->img}}" height="50px"></td>
            <td><a href="{{ route('exercise.show',$exercise->id) }}"><button type="button" class="btn btn-dark btn-sm">Edit</button></a></td>
            <td>
                <form action="{{ route('exercise.destroy',$exercise->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this exercise?')">Remove</button>
                </form>
            </td>
        </tr>

    @empty

        <p>No users</p>

    @endforelse

    <!-- Exercise Modal -->

    <div class="modal fade" id="addExercise">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Exercise</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('exercise.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <label>Exercise Name: </label> <input type="text" name="exercise" class="form-control" placeholder="e.g: Pushup" required>
                                    <input type="hidden" name="catagorie_id" value="{{$last_e + 1}}" class="form-control"><br>
                                    <select class="custom-select" name="catagorie_name"  required>
                                        <option selected>Select a Workout Category</option>
                                        @foreach($catagories as $category)
                                            <option value="{{$category->catagorie_name}}">{{$category->catagorie_name}}</option>
                                        @endforeach
                                    </select>

                                    <br><br>

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Exercise Description</label>
                                        <textarea class="form-control" name="description" id="description" rows="3"  required></textarea>
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Exercise Tips</label>
                                        <textarea class="form-control" name="tips" id="tips" rows="3"  required></textarea>
                                    </div>

                                    <input type="file" name="img" class="form-control" name="Upload Image"  required/>

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary" onclick="tinyMCE.triggerSave(true,true);">Add Category</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>



<script src="//code.jquery.com/jquery-3.3.1.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#profile-table').dataTable({

        columnDefs: [{
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        }],
        select: {
            style: 'os',
            selector: 'td:first-child'
        }
    });
</script>

resources/views/plugins/modals.blade.php
<!-- Large modal -->
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            ...
        </div>
    </div>
</div>

resources/views/plugins/notifications.blade.php
@if ($message = Session::get('deleted'))

    <body onload="notification()">

    <script>
        function notification() {

            $.notify("Category Deleted Successfully");

        }
    </script>
@endif

    @if ($message = Session::get('added'))

        <body onload="notification()">

        <script>
            function notification() {

                $.notify("Category Added Successfully");

            }
        </script>
@endif

        @if ($message = Session::get('updated1'))

            <body onload="notification()">

            <script>
                function notification() {

                    $.notify("Updated Successfully");

                }
            </script>
@endif
            @if ($message = Session::get('deletedb'))

                <body onload="notification()">

                <script>
                    function notification() {

                        $.notify("Blog Deleted Successfully");

                    }
                </script>
@endif

                @if ($message = Session::get('addedb'))

                    <body onload="notification()">

                    <script>
                        function notification() {

                            $.notify("Blog Added Successfully");

                        }
                    </script>
@endif

resources/views/plugins/nutrition-catagories.blade.php
<table class="table table-striped table-bordered display compact">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Catrgory ID</th>
        <th scope="col">Nutrition Catagories</th>
        <th><button type="button" class="tn btn-outline-light btn-sm" data-toggle="modal" data-target="#addNutrition" data-whatever="@getbootstrap">Add</button></th>
    </tr>
    </thead>
    <tbody>

    @forelse($nutrition as $key)

        <tr>
            <td>{{$key->catagorie_id}}</td>
            <td>{{$key->catagorie_name}}</td>
            <td>
                <form action="{{ route('nutritioncat.destroy',$key->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this category?')">Remove</button>
                </form>
            </td>
        </tr>

    @empty

        <p>No Catagories</p>

    @endforelse

    <!-- Category Modal -->

    <div class="modal fade" id="addNutrition" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('nutritioncat.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <input type="text" name="catagorie_name" class="form-control" placeholder="e.g: Fish" required>
                                    <input type="hidden" name="catagorie_id" value="{{$last_n + 1}}" class="form-control"><br>
                                    <input type="file" name="img" class="form-control"/>

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add Category</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>

resources/views/plugins/nutrition-table.blade.php
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" type="text/css">

<table id="profile-table" class="display">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Exercise Name</th>
        <th scope="col">Category Name</th>
        <th scope="col">Image</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    @forelse($nutritions as $nutrition)

        <tr>
            <td>{{$nutrition->id}}</td>
            <td>{{$nutrition->recipe}}</td>
            <td>{{$nutrition->catagorie_name}}</td>
            <td><img src="images/{{$nutrition->img}}" height="50px"></td>
            <td><a href="{{ route('nutrition.show',$nutrition->id) }}"><button type="button" class="btn btn-dark btn-sm">Edit</button></a></td>
            <td>
                <form action="{{ route('nutrition.destroy',$nutrition->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this exercise?')">Remove</button>
                </form>
            </td>
        </tr>

    @empty

        <p>No users</p>

    @endforelse

    <!-- Nutrition Modal -->

    <div class="modal fade" id="addRecipe">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Recipe</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('nutrition.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <label>Recipe Name: </label> <input type="text" name="recipe" class="form-control" placeholder="e.g: Pushup" required><br>
                                    <select class="custom-select" name="catagorie_name">
                                        <option selected>Select a Recipe Category</option>
                                        @foreach($catagories as $category)
                                            <option value="{{$category->catagorie_name}}">{{$category->catagorie_name}}</option>
                                        @endforeach
                                    </select>

                                    <br><br>

                                    <div class="form-group">
                                        <label for="exampleFormControlTextarea1">Recipe Description</label>
                                        <textarea class="form-control" name="description" id="description" rows="3"></textarea>
                                    </div>

                                    <label>Calories: </label> <input type="text" name="calories" class="form-control" placeholder="e.g: 600" required>
                                    <label>Carbs: </label> <input type="text" name="carbs" class="form-control" placeholder="e.g: 45" required>
                                    <label>Protein: </label> <input type="text" name="protein" class="form-control" placeholder="e.g: 60" required>
                                    <label>Fat: </label> <input type="text" name="fat" class="form-control" placeholder="e.g: 18" required>
                                    <br>
                                    <input type="file" name="img" class="form-control"  name="Upload Image"/>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary" onclick="tinyMCE.triggerSave(true,true);">Add Recipe</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>



<script src="//code.jquery.com/jquery-3.3.1.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#profile-table').dataTable({

        columnDefs: [{
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        }],
        select: {
            style: 'os',
            selector: 'td:first-child'
        }
    });
</script>

resources/views/plugins/profile-table.blade.php
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" type="text/css">


<table id="profile-table" class="display">
    <thead class="thead-dark">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    @forelse($profiles as $profile)

        <tr>
            <td>{{$profile->id}}</td>
            <td>{{$profile->name}}</td>
            <td>{{$profile->email}}</td>
            <td><a href="{{ route('view-profile.show',$profile->id) }}"><button type="button" class="btn btn-dark btn-sm">Edit</button></a></td>
        </tr>

    @empty

        <p>No users</p>

    @endforelse

    </tbody>
</table>



<script src="//code.jquery.com/jquery-3.3.1.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<script>
    $('#profile-table').dataTable({

        columnDefs: [{
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        }],
        select: {
            style: 'os',
            selector: 'td:first-child'
        }
    });
</script>

resources/views/plugins/store-catagories.blade.php
<table class="table table-striped table-bordered display compact">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Catrgory ID</th>
        <th scope="col">Store Catagories</th>
        <th><button type="button" class="tn btn-outline-light btn-sm" data-toggle="modal" data-target="#addStore" data-whatever="@getbootstrap">Add</button></th>
    </tr>
    </thead>
    <tbody>

    @forelse($stores as $store)

        <tr>
            <td>{{$store->catagorie_id}}</td>
            <td>{{$store->catagorie_name}}</td>
            <td>
                <form action="{{ route('storecat.destroy',$store->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this category?')">Remove</button>
                </form>
            </td>
             </tr>

    @empty

        <p>No Catagories</p>

    @endforelse
    
     <!-- Category Modal -->

    <div class="modal fade" id="addStore" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('storecat.store') }}" method="POST">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <input type="text" name="catagorie_name" class="form-control" placeholder="e.g: Protein" required>
                                    <input type="hidden" name="catagorie_id" value="{{$last_s + 1}}" class="form-control">

                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add Category</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>

resources/views/plugins/workout-catagories.blade.php
<table class="table table-striped table-bordered display compact" >
    <thead class="thead-dark">
    <tr>
        <th scope="col">Category ID</th>
        <th scope="col">Workout Categories</th>
        <th><button type="button" class="tn btn-outline-light btn-sm" data-toggle="modal" data-target="#addWorkout" data-whatever="@getbootstrap">Add</button></th>
       
    </tr>
    </thead>
    <tbody>

    @forelse($catagories as $catagorie)

        <tr>
            <td>{{$catagorie->catagorie_id}}</td>
            <td>{{$catagorie->catagorie_name}}</td>
            <td>
                <form action="{{ route('exercisecat.destroy',$catagorie->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-dark btn-sm" onclick="return confirm('Are you sure you want to remove this category?')">Remove</button>
                </form>
            </td>
             </tr>

    @empty

        <p>No Catagories</p>

    @endforelse
    
        <!-- Category Modal -->

    <div class="modal fade" id="addWorkout" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add a New Category</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('exercisecat.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group container">
                                    <input type="text" name="catagorie_name" class="form-control" placeholder="e.g: Arms" required>
                                    <input type="hidden" name="catagorie_id" value="{{$last_w + 1}}" class="form-control"><br>
                                    <input type="file" name="img" class="form-control"/>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Add Category</button>
                            </div>
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    </tbody>
</table>