routes/web.php
<?php
use App\Applicant;
use App\User;
use App\Week;
use App\Store;
use App\Storecat;
use App\Profile;
use App\Exercise;
use App\Exercisecat;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});


Route::get('test', function(){ return '';});

Route::resource('profile', 'ProfileController');
Route::resource('nutrition', 'NutritionController');
Route::resource('nutritioncat', 'NutritioncatController');
Route::resource('exercise', 'ExerciseController');
Route::resource('exercisecat', 'ExercisecatController');
Route::resource('storecat', 'StorecatController');
Route::resource('view-profile', 'ViewProfileController');
Route::resource('categories', 'CategoriesController');
Route::resource('blogs', 'BlogController');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $fillable = ['user_id','dob','height','weight','age','sex','ethnic'];

    public function user(){
        return $this->hasOne(User::class);
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Profile;
use App\User;
use App\Exercisecat;
use App\Nutritioncat;
use App\Storecat;

class ProfileController extends Controller
{

    public function __construct()
    {

//        $this->middleware('auth.basic');

    }

    public function index()
    {

        $profiles = User::all();
        $catagories = Exercisecat::orderBy('id', 'asc')->get();
        $nutrition = Nutritioncat::orderBy('id', 'asc')->get();
        $stores = Storecat::orderBy('id', 'asc')->get();
        $lastid_n = Nutritioncat::orderBy('id', 'desc')->first();
        $last_n = $lastid_n['id'];
        $lastid_w = Exercisecat::orderBy('id', 'desc')->first();
        $last_w = $lastid_w['id'];
        $lastid_s = Storecat::orderBy('id', 'desc')->first();
        $last_s = $lastid_s['id'];
        return view('profiles.index', compact('profiles','catagories', 'nutrition', 'stores','last_n','last_w','last_s'));



    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        $update = Profile::findOrFail($id);
        $update->dob= $request->dob;
        $update->height = $request->height;
        $update->weight = $request->weight;
        $update->age = $request->age;
        $update->sex = $request->sex;
        $update->ethnic = $request->ethnic;
        $update->save();

        return redirect()->back()->with('updated1','true');
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/profiles/index.blade.php
@extends('layouts.app')


@section('content')

    @include('plugins.notifications')
    
        <div class="row">

        <div class="container">
                <div class="col-12">

                    <table class="table table-striped table-bordered">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Profiles</th>

                        </thead>
                        <tbody>


                        </tbody>
                    </table>
                </div>

                <div class="col-12">

                @include('plugins.profile-table')

                </div>
        </div>
            </div>


@endsection

resources/views/profiles/view.blade.php
@extends('layouts.app')


@section('content')

    <style>
        .user-row {
            margin-bottom: 14px;
        }

        .user-row:last-child {
            margin-bottom: 0;
        }

        .table-user-information > tbody > tr {
            border-top: 1px solid rgb(221, 221, 221);
        }

        .table-user-information > tbody > tr:first-child {
            border-top: 0;
        }


        .table-user-information > tbody > tr > td {
            border-top: 0;
        }
        .toppad
        {margin-top:20px;
        }
    </style>

    @include('plugins.notifications')

    <div class="container">
        <div class="row">
            <div class="col-md-12  toppad  offset-md-0 ">
                <a href="{{ URL::previous() }}" class="btn btn-dark btn float-right">Go Back</a>
            </div>
            <div class="col-md-6  offset-md-0  toppad" >
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">User Information</h3>
                        <form action="{{ route('view-profile.update',$user->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                        <table class="table table-user-information ">
                            <tbody>
                            <tr>
                                <td>Name:</td>
                                <td><input class="form-control" type="text" name="name" value="{{$user->name}}"></td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td><input class="form-control" type="text" name="email" value="{{$user->email}}"></td>
                            </tr>
                            <tr>
                                <td>Membership Started:</td>
                                <td><input class="form-control" type="text"  value="{{$user->created_at}}" disabled></td>
                            </tr>
                            <tr>
                                <td>Last Update:</td>
                                <td><input class="form-control" type="text"  value="{{$user->updated_at}}" disabled></td>
                            </tr>
                            </tbody>
                        </table>
                            <button type="submit" class="btn btn-dark btn" onclick="return confirm('Are you sure you want to save these changes?')">Save Changes</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-6  offset-md-0  toppad" >
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Profile Information</h3>
                        <form action="{{ route('profile.update',$profile->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                        <table class="table table-user-information ">
                            <tbody>
                            <tr>
                                <td>Date Of Birth:</td>
                                <td><input class="form-control" type="text" name="dob" value="{{$profile->dob}}"></td>
                            </tr>
                            <tr>
                                <td>Height:</td>
                                <td><input class="form-control" type="text" name="height" value="{{$profile->height}}"></td>
                            </tr>
                            <tr>
                                <td>Weight:</td>
                                <td><input class="form-control" type="text" name="weight" value="{{$profile->weight}}"></td>
                            </tr>
                            <tr>
                                <td>Age:</td>
                                <td><input class="form-control" type="text" name="age" value="{{$profile->age}}"></td>
                            </tr>
                            <tr>
                                <td>Sex:</td>
                                <td><input class="form-control" type="text" name="sex" value="{{$profile->sex}}"></td>
                            </tr>
                            <tr>
                                <td>Ethnic:</td>
                                <td><input class="form-control" type="text" name="ethnic" value="{{$profile->ethnic}}"></td>
                            </tr>
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-dark btn" onclick="return confirm('Are you sure you want to save these changes?')">Save Changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection